FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["FileDivider.Api.csproj", "FileDivider.Api/"]
RUN dotnet restore "FileDivider.Api/FileDivider.Api.csproj"

WORKDIR "/src/FileDivider.Api"
COPY . .

RUN dotnet build "FileDivider.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FileDivider.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FileDivider.Api.dll"]